/* cat89_free.c - free category generated by a directed graph. */

#include "cat89_internal.h"
#include <cat89/free.h>

struct fv
{
    const void *vertex;
    struct fv *next;
};

struct fmor
{
    unsigned long refs;
    const struct fv *dom;
    const struct fv *cod;
    unsigned long len;
    const void **edges;
    struct fmor *next_live;
};

struct free_ctx
{
    cat89_allocator allocator;
    cat89_free_graph_ops ops;
    void *graph_ctx;
    struct fv *vertices;
    struct fmor *live_mors;
    cat89_category *category;
};

static const struct fv *fv_cread(const cat89_obj *obj)
{
    return (const struct fv *)(const void *)obj;
}

static int free_obj_same_cb(void *ctx, const cat89_obj *a, const cat89_obj *b)
{
    struct free_ctx *fc = ctx;
    const struct fv *x;
    const struct fv *y;

    int result;

    x = fv_cread(a);
    y = fv_cread(b);
    result = fc->ops.vertex_same(fc->graph_ctx, x->vertex, y->vertex);
    return result;
}

static struct fv *find_vertex(struct free_ctx *fc, const void *vertex)
{
    struct fv *o;
    int same;

    for (o = fc->vertices; o != NULL; o = o->next)
    {
        same = fc->ops.vertex_same(fc->graph_ctx, o->vertex, vertex);
        if (same)
        {
            return o;
        }
    }
    return NULL;
}

static cat89_status intern_vertex(struct free_ctx *fc, const void *vertex,
                                  struct fv **out)
{
    struct fv *o;

    o = find_vertex(fc, vertex);
    if (o != NULL)
    {
        *out = o;
        return CAT89_OK;
    }
    o = cat89_alloc(&fc->allocator, sizeof(*o));
    if (o == NULL)
    {
        return CAT89_NOMEM;
    }
    o->vertex = vertex;
    o->next = fc->vertices;
    fc->vertices = o;
    *out = o;
    return CAT89_OK;
}

static const struct fmor *mor_cread(const cat89_mor *mor)
{
    return (const struct fmor *)(const void *)mor;
}

static cat89_status free_dom_cb(void *ctx, const cat89_mor *mor,
                                const cat89_obj **out_obj)
{
    const struct fmor *m;

    (void)ctx;
    m = mor_cread(mor);
    *out_obj = (const cat89_obj *)m->dom;
    return CAT89_OK;
}

static cat89_status free_cod_cb(void *ctx, const cat89_mor *mor,
                                const cat89_obj **out_obj)
{
    const struct fmor *m;

    (void)ctx;
    m = mor_cread(mor);
    *out_obj = (const cat89_obj *)m->cod;
    return CAT89_OK;
}

static void edge_copy(const void **dst, const void **src, unsigned long i);

static cat89_status copy_edges(struct free_ctx *fc, unsigned long len,
                               const void **src, const void ***out)
{
    const void **copy;
    unsigned long i;

    *out = NULL;
    if (len == 0)
    {
        return CAT89_OK;
    }
    copy = cat89_alloc(&fc->allocator, len * sizeof(const void *));
    if (copy == NULL)
    {
        return CAT89_NOMEM;
    }
    for (i = 0; i < len; i = i + 1)
    {
        edge_copy(copy, src, i);
    }
    *out = copy;
    return CAT89_OK;
}

static cat89_status mor_make(struct free_ctx *fc, const struct fv *dom,
                             const struct fv *cod, unsigned long len,
                             const void **edges, cat89_mor **out_mor)
{
    struct fmor *m;
    const void **copy;
    cat89_status st;

    st = copy_edges(fc, len, edges, &copy);
    if (st != CAT89_OK)
    {
        return st;
    }
    m = cat89_alloc(&fc->allocator, sizeof(*m));
    if (m == NULL)
    {
        if (copy != NULL)
        {
            cat89_free(&fc->allocator, copy);
        }
        return CAT89_NOMEM;
    }
    m->refs = 1;
    m->dom = dom;
    m->cod = cod;
    m->len = len;
    m->edges = copy;
    m->next_live = fc->live_mors;
    fc->live_mors = m;
    *out_mor = (cat89_mor *)m;
    return CAT89_OK;
}

static cat89_status free_identity_cb(void *ctx, const cat89_obj *obj,
                                     cat89_mor **out_mor)
{
    struct free_ctx *fc = ctx;
    const struct fv *o;
    cat89_status st;

    o = fv_cread(obj);
    st = mor_make(fc, o, o, 0, NULL, out_mor);
    return st;
}

static void edge_copy(const void **dst, const void **src, unsigned long i)
{
    dst[i] = src[i];
}

static void edge_copy_shift(const void **dst, const void **src,
                            unsigned long shift, unsigned long i)
{
    dst[shift + i] = src[i];
}

static cat89_status free_compose_cb(void *ctx, const cat89_mor *g,
                                    const cat89_mor *f, cat89_mor **out_mor)
{
    struct free_ctx *fc = ctx;
    const struct fmor *gm;
    const struct fmor *fm;
    const void **edges;
    unsigned long total;
    unsigned long i;
    cat89_status st;

    gm = mor_cread(g);
    fm = mor_cread(f);

    if (fm->len == 0)
    {
        st = mor_make(fc, fm->dom, gm->cod, gm->len, gm->edges, out_mor);
        return st;
    }
    if (gm->len == 0)
    {
        st = mor_make(fc, fm->dom, gm->cod, fm->len, fm->edges, out_mor);
        return st;
    }

    total = fm->len + gm->len;
    edges = cat89_alloc(&fc->allocator, total * sizeof(const void *));
    if (edges == NULL)
    {
        return CAT89_NOMEM;
    }
    for (i = 0; i < fm->len; i = i + 1)
    {
        edge_copy(edges, fm->edges, i);
    }
    for (i = 0; i < gm->len; i = i + 1)
    {
        edge_copy_shift(edges, gm->edges, fm->len, i);
    }
    st = mor_make(fc, fm->dom, gm->cod, total, edges, out_mor);
    if (st != CAT89_OK)
    {
        cat89_free(&fc->allocator, edges);
        return st;
    }
    cat89_free(&fc->allocator, edges);
    return CAT89_OK;
}

static cat89_status free_retain_cb(void *ctx, cat89_mor *mor)
{
    struct fmor *m;
    cat89_status st;

    (void)ctx;
    m = (struct fmor *)mor;
    st = cat89_ref_inc(&m->refs);
    return st;
}

static int free_mor_drop(struct fmor *m)
{
    int dropped;

    dropped = cat89_ref_dec(&m->refs);
    return dropped;
}

static struct fmor **free_mor_unlink_next(struct fmor **link)
{
    return &(*link)->next_live;
}

static void free_mor_unlink_remove(struct fmor **link, struct fmor *m)
{
    *link = m->next_live;
}

static void free_mor_unlink(struct free_ctx *fc, struct fmor *m)
{
    struct fmor **link;

    link = &fc->live_mors;
    while (*link != NULL)
    {
        if (*link == m)
        {
            free_mor_unlink_remove(link, m);
            return;
        }
        link = free_mor_unlink_next(link);
    }
}

static void free_release_cb(void *ctx, cat89_mor *mor)
{
    struct free_ctx *fc = ctx;
    struct fmor *m;
    int last;

    m = (struct fmor *)mor;
    last = free_mor_drop(m);
    if (last)
    {
        free_mor_unlink(fc, m);
        if (m->edges != NULL)
        {
            cat89_free(&fc->allocator, m->edges);
        }
        cat89_free(&fc->allocator, m);
    }
}

static struct fv *free_vertex_one(struct free_ctx *fc, struct fv *o)
{
    struct fv *next;

    next = o->next;
    cat89_free(&fc->allocator, o);
    return next;
}

static void free_destroy_cb(void *ctx)
{
    struct free_ctx *fc = ctx;
    struct fv *o;

    o = fc->vertices;
    while (o != NULL)
    {
        o = free_vertex_one(fc, o);
    }
    cat89_free(&fc->allocator, fc);
}

static int free_owns_obj_cb(void *ctx, const cat89_obj *obj)
{
    struct free_ctx *fc = ctx;
    struct fv *o;

    for (o = fc->vertices; o != NULL; o = o->next)
    {
        if ((const cat89_obj *)(const void *)o == obj)
        {
            return 1;
        }
    }
    return 0;
}

static int free_owns_mor_cb(void *ctx, const cat89_mor *mor)
{
    struct free_ctx *fc = ctx;
    struct fmor *m;

    for (m = fc->live_mors; m != NULL; m = m->next_live)
    {
        if ((const cat89_mor *)(const void *)m == mor)
        {
            return 1;
        }
    }
    return 0;
}

static const cat89_category_ops free_ops = {
    free_dom_cb,      free_cod_cb,    free_identity_cb, free_compose_cb,
    free_obj_same_cb, free_retain_cb, free_release_cb,  free_owns_obj_cb,
    free_owns_mor_cb, free_destroy_cb};

static const cat89_allocator *resolve_alloc(const cat89_allocator *allocator)
{
    const cat89_allocator *actual;

    if (allocator == NULL)
    {
        actual = cat89_allocator_default();
    }
    else
    {
        actual = allocator;
    }
    return actual;
}

cat89_status cat89_free_category_new(const cat89_free_graph_ops *ops,
                                     void *graph_ctx,
                                     const cat89_allocator *allocator,
                                     cat89_category **out_category)
{
    struct free_ctx *fc;
    const cat89_allocator *actual;
    cat89_status st;

    if (out_category == NULL)
    {
        return CAT89_INVALID;
    }
    *out_category = NULL;
    if (ops == NULL)
    {
        return CAT89_INVALID;
    }
    if (ops->vertex_same == NULL)
    {
        return CAT89_INVALID;
    }
    if (ops->edge_source == NULL)
    {
        return CAT89_INVALID;
    }
    if (ops->edge_target == NULL)
    {
        return CAT89_INVALID;
    }

    actual = resolve_alloc(allocator);

    fc = cat89_alloc(actual, sizeof(*fc));
    if (fc == NULL)
    {
        return CAT89_NOMEM;
    }
    fc->allocator = *actual;
    fc->ops = *ops;
    fc->graph_ctx = graph_ctx;
    fc->vertices = NULL;
    fc->live_mors = NULL;
    fc->category = NULL;

    st = cat89_category_new(&free_ops, fc, actual, &fc->category);
    if (st != CAT89_OK)
    {
        cat89_free(actual, fc);
        return st;
    }
    *out_category = fc->category;
    return CAT89_OK;
}

cat89_status cat89_free_obj(cat89_category *category, const void *vertex,
                            const cat89_obj **out_obj)
{
    struct free_ctx *fc;
    struct fv *o;
    cat89_status st;

    if (out_obj == NULL)
    {
        return CAT89_INVALID;
    }
    *out_obj = NULL;
    if (category == NULL)
    {
        return CAT89_INVALID;
    }
    if (vertex == NULL)
    {
        return CAT89_INVALID;
    }
    fc = cat89_category_ctx(category);
    st = intern_vertex(fc, vertex, &o);
    if (st != CAT89_OK)
    {
        return st;
    }
    *out_obj = (const cat89_obj *)o;
    return CAT89_OK;
}

cat89_status cat89_free_edge(cat89_category *category, const void *edge,
                             cat89_mor **out_mor)
{
    struct free_ctx *fc;
    struct fv *src;
    struct fv *dst;
    const void *svertex;
    const void *tvertex;
    const void *single;
    cat89_status st;

    if (out_mor == NULL)
    {
        return CAT89_INVALID;
    }
    *out_mor = NULL;
    if (category == NULL)
    {
        return CAT89_INVALID;
    }
    if (edge == NULL)
    {
        return CAT89_INVALID;
    }
    fc = cat89_category_ctx(category);

    svertex = fc->ops.edge_source(fc->graph_ctx, edge);
    tvertex = fc->ops.edge_target(fc->graph_ctx, edge);
    st = intern_vertex(fc, svertex, &src);
    if (st != CAT89_OK)
    {
        return st;
    }
    st = intern_vertex(fc, tvertex, &dst);
    if (st != CAT89_OK)
    {
        return st;
    }
    single = edge;
    st = mor_make(fc, src, dst, 1, &single, out_mor);
    return st;
}
