/* Generated by tools/gen_unicode_tables.py -- Unicode 17.0.0. */
#ifndef U89_TABLES_H
#define U89_TABLES_H

#include "../include/u89.h"

/* width type: 0 control, 1 zero-width, 2 wide, 3 ambiguous, 4 narrow */
typedef struct u89_wrange { u89_cp lo; u89_cp hi; unsigned char type; } u89_wrange;
extern const u89_wrange u89_width_ranges[];
extern const size_t u89_width_count;

typedef struct u89_range { u89_cp lo; u89_cp hi; } u89_range;
extern const u89_range u89_xid_start_ranges[];
extern const size_t u89_xid_start_count;
extern const u89_range u89_xid_cont_ranges[];
extern const size_t u89_xid_cont_count;
extern const u89_range u89_id_start_ranges[];
extern const size_t u89_id_start_count;
extern const u89_range u89_id_cont_ranges[];
extern const size_t u89_id_cont_count;
extern const u89_range u89_defign_ranges[];
extern const size_t u89_defign_count;
extern const u89_range u89_patws_ranges[];
extern const size_t u89_patws_count;
extern const u89_range u89_patsyn_ranges[];
extern const size_t u89_patsyn_count;
extern const u89_range u89_join_ranges[];
extern const size_t u89_join_count;

typedef struct u89_prop_range { u89_cp lo; u89_cp hi; unsigned short value; } u89_prop_range;
extern const u89_prop_range u89_gc_ranges[];
extern const size_t u89_gc_count;
extern const u89_prop_range u89_gcb_ranges[];
extern const size_t u89_gcb_count;
extern const u89_prop_range u89_incb_ranges[];
extern const size_t u89_incb_count;
extern const u89_prop_range u89_eaw_ranges[];
extern const size_t u89_eaw_count;

extern const u89_range u89_emoji_ranges[];
extern const size_t u89_emoji_count;
extern const u89_range u89_emoji_pres_ranges[];
extern const size_t u89_emoji_pres_count;
extern const u89_range u89_extpict_ranges[];
extern const size_t u89_extpict_count;

typedef struct u89_crange { u89_cp lo; u89_cp hi; unsigned char ccc; } u89_crange;
extern const u89_crange u89_ccc_ranges[];
extern const size_t u89_ccc_count;

typedef struct u89_mapping { u89_cp cp; unsigned long offset; unsigned short length; } u89_mapping;
extern const u89_cp u89_mapping_pool[];
extern const size_t u89_mapping_pool_count;
extern const u89_mapping u89_canon[];
extern const size_t u89_canon_count;
extern const u89_mapping u89_compat[];
extern const size_t u89_compat_count;
extern const u89_mapping u89_casefold_map[];
extern const size_t u89_casefold_map_count;
extern const u89_mapping u89_casefold_turkic_map[];
extern const size_t u89_casefold_turkic_map_count;

typedef struct u89_comp { u89_cp first; u89_cp second; u89_cp result; } u89_comp;
extern const u89_comp u89_comp_tbl[];
extern const size_t u89_comp_count;

#endif
