#ifndef HM_H
#define HM_H

/* hm.h - Generic Hindley-Milner type inference library for ISO C89.
 *
 * Public contract (spec sections 6-18, 27-30, 51). This header declares
 * only the primitive generic API. No AST, source language, or built-in
 * type is prescribed by this library.
 */

#include <stddef.h>

/* Opaque public types. Their representation is private. */
typedef struct hm_ctx hm_ctx;
typedef struct hm_type hm_type;
typedef struct hm_scheme hm_scheme;
typedef struct hm_env hm_env;
typedef struct hm_error hm_error;

/* Status values returned by operations. */
typedef enum hm_status
{
    HM_OK = 0,
    HM_ERROR_NOMEM,
    HM_ERROR_MISMATCH,
    HM_ERROR_OCCURS,
    HM_ERROR_UNBOUND,
    HM_ERROR_INVALID,
    HM_ERROR_INTERNAL
} hm_status;

/* Public category of a type node. */
typedef enum hm_type_kind
{
    HM_TYPE_VAR,
    HM_TYPE_CON
} hm_type_kind;

/* Structured error kinds. */
typedef enum hm_error_kind
{
    HM_ERR_NONE = 0,
    HM_ERR_NOMEM,
    HM_ERR_MISMATCH,
    HM_ERR_OCCURS,
    HM_ERR_UNBOUND,
    HM_ERR_INVALID,
    HM_ERR_INTERNAL
} hm_error_kind;

/* Allocation callbacks. Passing a NULL allocator to hm_ctx_new selects
 * malloc/free. */
typedef void *(*hm_alloc_fn)(void *userdata, size_t size);
typedef void (*hm_free_fn)(void *userdata, void *ptr);

typedef struct hm_allocator
{
    hm_alloc_fn alloc;
    hm_free_fn free;
    void *userdata;
} hm_allocator;

/* Output callback used by the renderers. */
typedef int (*hm_write_fn)(void *userdata, const char *data, size_t size);

/* ------------------------------------------------------------------ */
/* Context lifecycle                                                  */
/* ------------------------------------------------------------------ */

hm_ctx *hm_ctx_new(const hm_allocator *allocator);
void hm_ctx_destroy(hm_ctx *ctx);

/* Associate an opaque origin pointer with the context; errors generated by
 * later operations capture it. The library never dereferences it. */
void hm_ctx_set_origin(hm_ctx *ctx, void *origin);

/* ------------------------------------------------------------------ */
/* Type representation                                                */
/* ------------------------------------------------------------------ */

hm_type_kind hm_type_kind_of(hm_type *type);

/* Fresh type variable carrying a stable id. */
hm_type *hm_type_var(hm_ctx *ctx);
unsigned long hm_type_var_id(hm_type *type);

/* Named n-ary constructor application; name is copied. */
hm_type *hm_type_con(hm_ctx *ctx, const char *name, size_t arity,
                     hm_type **args);

/* Convenience constructor helpers. */
hm_type *hm_type_const(hm_ctx *ctx, const char *name);
hm_type *hm_type_app1(hm_ctx *ctx, const char *name, hm_type *a);
hm_type *hm_type_app2(hm_ctx *ctx, const char *name, hm_type *a, hm_type *b);
hm_type *hm_type_fun(hm_ctx *ctx, hm_type *arg, hm_type *result);

/* Follow variable links to an unbound variable or constructor, with path
 * compression. */
hm_type *hm_type_prune(hm_type *type);

/* Public constructor introspection. These prune before inspecting and
 * describe only named n-ary type constructors. */
const char *hm_type_con_name(hm_type *type);
size_t hm_type_con_arity(hm_type *type);
hm_type *hm_type_con_arg(hm_type *type, size_t index);

/* Structural equality after pruning; never mutates except path compression. */
int hm_type_equal(hm_type *a, hm_type *b);

/* ------------------------------------------------------------------ */
/* Unification                                                        */
/* ------------------------------------------------------------------ */

hm_status hm_unify(hm_ctx *ctx, hm_type *left, hm_type *right,
                   hm_error **error);

/* ------------------------------------------------------------------ */
/* Schemes                                                            */
/* ------------------------------------------------------------------ */

hm_scheme *hm_scheme_mono(hm_ctx *ctx, hm_type *type);
hm_scheme *hm_scheme_new(hm_ctx *ctx, size_t quantified_count,
                         hm_type **quantified, hm_type *body);
size_t hm_scheme_quantified_count(const hm_scheme *scheme);
hm_type *hm_scheme_body(const hm_scheme *scheme);

hm_type *hm_instantiate(hm_ctx *ctx, const hm_scheme *scheme);
hm_scheme *hm_generalize(hm_ctx *ctx, hm_env *env, hm_type *type);

/* ------------------------------------------------------------------ */
/* Environments                                                       */
/* ------------------------------------------------------------------ */

hm_env *hm_env_new(hm_ctx *ctx);
hm_env *hm_env_child(hm_ctx *ctx, hm_env *parent);

hm_status hm_env_bind(hm_env *env, const char *name, hm_scheme *scheme);
hm_scheme *hm_env_lookup(hm_env *env, const char *name);

/* ------------------------------------------------------------------ */
/* Errors                                                             */
/* ------------------------------------------------------------------ */

hm_error_kind hm_error_kind_of(const hm_error *error);
const char *hm_error_message(const hm_error *error);
hm_type *hm_error_left(const hm_error *error);
hm_type *hm_error_right(const hm_error *error);
const char *hm_error_name(const hm_error *error);
void *hm_error_origin(const hm_error *error);

/* ------------------------------------------------------------------ */
/* Rendering                                                          */
/* ------------------------------------------------------------------ */

hm_status hm_type_write(hm_type *type, hm_write_fn write_fn, void *userdata);
hm_status hm_scheme_write(const hm_scheme *scheme, hm_write_fn write_fn,
                          void *userdata);

#endif /* HM_H */
