#ifndef ADT_H
#define ADT_H

/* adt.h - nominal algebraic datatype declarations and analysis on top of
 * libhm89 (ISO C89).
 *
 * libadt89 lowers ordinary ML-style datatype declarations into the generic
 * libhm89 representation: named n-ary type constructors plus polymorphic
 * value-constructor schemes. It adds declaration metadata, constructor
 * scheme generation, environment installation, constructor-pattern typing,
 * and exhaustiveness/redundancy analysis. It implements no second type
 * system and defines no runtime value representation.
 *
 * Ownership: an adt_ctx owns its declarations, constructors, patterns, and
 * last error. The underlying hm_ctx is NOT owned by adt_ctx; adt_ctx_destroy
 * never frees HM objects, so the hm_ctx MUST outlive the adt_ctx and be
 * destroyed only after adt_ctx_destroy.
 */

#include <stddef.h>

#include <hm.h>

/* Opaque public types. Their representation is private. */
typedef struct adt_ctx adt_ctx;
typedef struct adt_type adt_type;
typedef struct adt_ctor adt_ctor;
typedef struct adt_error adt_error;
typedef struct adt_pattern adt_pattern;

/* Allocation callbacks. Passing a NULL allocator to adt_ctx_new selects
 * malloc/free. The allocator mirrors hm_allocator. */
typedef void *(*adt_alloc_fn)(void *userdata, size_t size);
typedef void (*adt_free_fn)(void *userdata, void *ptr);

typedef struct adt_allocator
{
    adt_alloc_fn alloc;
    adt_free_fn free;
    void *userdata;
} adt_allocator;

/* Status values returned by operations. */
typedef enum adt_status
{
    ADT_OK = 0,
    ADT_ERROR_NOMEM,
    ADT_ERROR_INVALID,
    ADT_ERROR_DUPLICATE_TYPE,
    ADT_ERROR_DUPLICATE_CTOR,
    ADT_ERROR_WRONG_ARITY,
    ADT_ERROR_UNSEALED,
    ADT_ERROR_SEALED,
    ADT_ERROR_UNKNOWN_CTOR,
    ADT_ERROR_PATTERN_ARITY,
    ADT_ERROR_TYPE,
    ADT_ERROR_INTERNAL
} adt_status;

/* Structured error kinds. */
typedef enum adt_error_kind
{
    ADT_ERR_NONE = 0,
    ADT_ERR_DUPLICATE_TYPE,
    ADT_ERR_DUPLICATE_CTOR,
    ADT_ERR_WRONG_TYPE_ARITY,
    ADT_ERR_WRONG_PATTERN_ARITY,
    ADT_ERR_UNSEALED,
    ADT_ERR_SEALED,
    ADT_ERR_HM,
    ADT_ERR_INVALID
} adt_error_kind;

/* Pattern forms understood by the match-analysis subsystem. The MVP treats
 * variable and literal subpatterns as wildcards from this library's
 * perspective. */
typedef enum adt_pattern_kind
{
    ADT_PATTERN_WILDCARD,
    ADT_PATTERN_CTOR
} adt_pattern_kind;

/* Result of an exhaustiveness query. */
typedef enum adt_match_result
{
    ADT_MATCH_EXHAUSTIVE,
    ADT_MATCH_NONEXHAUSTIVE
} adt_match_result;

/* ------------------------------------------------------------------ */
/* Context lifecycle                                                  */
/* ------------------------------------------------------------------ */

adt_ctx *adt_ctx_new(hm_ctx *hm);
adt_ctx *adt_ctx_new_with_allocator(hm_ctx *hm, const adt_allocator *allocator);
void adt_ctx_destroy(adt_ctx *ctx);

/* Associate an opaque origin pointer with the context; errors generated by
 * later operations capture it. The library never dereferences it. */
void adt_ctx_set_origin(adt_ctx *ctx, void *origin);

/* Last structured error recorded on the context by a failing operation, or
 * NULL when the last operation succeeded. */
const adt_error *adt_ctx_error(const adt_ctx *ctx);

/* ------------------------------------------------------------------ */
/* Type declarations                                                  */
/* ------------------------------------------------------------------ */

/* Begin an OPEN declaration of an n-ary datatype. The display name may repeat
 * across declarations; each declaration receives a distinct nominal identity
 * observable through HM equality/unification. */
adt_type *adt_type_new(adt_ctx *ctx, const char *name, size_t parameter_count);

const char *adt_type_name(const adt_type *type);

size_t adt_type_parameter_count(const adt_type *type);

/* Declaration-template parameter variables. Callers MUST NOT unify these
 * during ordinary expression inference. */
hm_type *adt_type_parameter(const adt_type *type, size_t index);

/* Build the HM application T(arg0, ..., argn). Requires argument_count to
 * equal the declared parameter count; otherwise returns NULL and records
 * ADT_ERROR_WRONG_ARITY. */
hm_type *adt_type_apply(adt_type *type, size_t argument_count,
                        hm_type **arguments);

/* ------------------------------------------------------------------ */
/* Constructors                                                       */
/* ------------------------------------------------------------------ */

/* Add a constructor while the owner is OPEN. Constructor names share one
 * namespace per adt_ctx. field_types holds declaration-template types. */
adt_ctor *adt_ctor_add(adt_type *owner, const char *name, size_t field_count,
                       hm_type **field_types);

/* Close the constructor set, validate, and generate constructor schemes.
 * Afterwards the declaration is immutable. */
adt_status adt_type_seal(adt_type *type);

int adt_type_sealed(const adt_type *type);

size_t adt_type_ctor_count(const adt_type *type);
adt_ctor *adt_type_ctor(const adt_type *type, size_t index);

const char *adt_ctor_name(const adt_ctor *ctor);
adt_type *adt_ctor_owner(const adt_ctor *ctor);
size_t adt_ctor_field_count(const adt_ctor *ctor);
hm_type *adt_ctor_field_type(const adt_ctor *ctor, size_t index);

/* Immutable template scheme of a sealed constructor. NULL while OPEN. */
const hm_scheme *adt_ctor_scheme(const adt_ctor *ctor);

/* ------------------------------------------------------------------ */
/* Environment installation                                            */
/* ------------------------------------------------------------------ */

adt_status adt_type_bind(adt_type *type, hm_env *env);
adt_status adt_ctx_bind_all(adt_ctx *ctx, hm_env *env);

/* ------------------------------------------------------------------ */
/* Constructor-pattern typing                                          */
/* ------------------------------------------------------------------ */

/* Type a constructor applied to subpatterns against a scrutinee type.
 * Requires output_count == ctor field count. Instantiates the constructor
 * scheme, unifies its result against scrutinee_type, and writes the pruned
 * field types into out_field_types[0..field_count). */
adt_status adt_pattern_types(adt_ctx *ctx, adt_ctor *ctor,
                             hm_type *scrutinee_type, size_t output_count,
                             hm_type **out_field_types,
                             hm_error **out_hm_error);

/* ------------------------------------------------------------------ */
/* Match analysis                                                     */
/* ------------------------------------------------------------------ */

adt_pattern *adt_pattern_wildcard(adt_ctx *ctx);

adt_pattern *adt_pattern_ctor(adt_ctx *ctx, adt_ctor *ctor,
                              size_t argument_count, adt_pattern **arguments);

/* Exhaustiveness over a sealed type's top-level constructor family.
 * patterns is one pattern per clause, each matching the scrutinee `type`. */
adt_status adt_match_exhaustive(adt_type *type, size_t pattern_count,
                                adt_pattern **patterns,
                                adt_match_result *result);

/* Mark each clause pattern redundant when it matches nothing not already
 * matched by preceding clauses. out_redundant[i] is non-zero iff redundant. */
adt_status adt_match_redundant(size_t pattern_count, adt_pattern **patterns,
                               unsigned char *out_redundant);

/* ------------------------------------------------------------------ */
/* Errors                                                             */
/* ------------------------------------------------------------------ */

adt_error_kind adt_error_kind_of(const adt_error *error);
const char *adt_error_message(const adt_error *error);
const adt_type *adt_error_type(const adt_error *error);
const adt_ctor *adt_error_ctor(const adt_error *error);
const hm_error *adt_error_hm(const adt_error *error);
void *adt_error_origin(const adt_error *error);

#endif /* ADT_H */
