#!/usr/bin/env python3
"""Deterministic generator for the strict-suite case tables.

Run via `just gen-strict-tables`; the committed output under test/strict/
is the source of truth. Every emitted row is executed by a case module in
the fast, full, or long tier as documented in the table's header.
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
HEADER = "# Generated by gen_tables.py; do not edit by hand.\n"

UINT32_MAX = 0xFFFFFFFF
UINT64_MAX = 0xFFFFFFFFFFFFFFFF
MAX_RECORD = 16777216


def row(*fields):
    return "    (%s),\n" % ", ".join(repr(field) for field in fields)


def emit(filename, header, sections):
    path = os.path.join(HERE, filename)
    with open(path, "w") as handle:
        handle.write(HEADER)
        handle.write(header)
        for name, rows in sections:
            handle.write("\n%s = [\n" % name)
            for line in rows:
                handle.write(line)
            handle.write("]\n")
    return path


# ---------------------------------------------------------------------------
# API tables
# ---------------------------------------------------------------------------

BOUNDARY_VALUES = [
    0,
    1,
    2,
    3,
    7,
    8,
    0x7F,
    0x80,
    0xFF,
    0x100,
    0x101,
    0x7FFF,
    0x8000,
    0xFFFF,
    0x10000,
    0x10001,
    0x7FFFFFFF,
    0x80000000,
    0xFFFFFFFF,
    0x100000000,
    0x100000001,
    0x7FFFFFFFFFFFFFFF,
    0x8000000000000000,
    0xFFFFFFFFFFFFFFFE,
    0xFFFFFFFFFFFFFFFF,
]

PAYLOAD_SIZES = (
    list(range(0, 65))
    + [127, 128, 255, 256, 511, 512, 1023, 1024, 2047, 2048, 4095, 4096,
       8191, 8192, 65535, 65536, 1048575, 1048576, 16777215, 16777216,
       16777217, 0x7FFFFFFFFFFFFFFF]
)

OPEN_SPECIAL_FLAGS = [
    0x100,
    0x8000,
    0x10000,
    0xFFFFFFFF,
    0x00010003,
    0x00020004,
    0x00080004,
    0x000A0004,
]


def open_rows():
    rows = []
    flag_values = list(range(0, 256)) + OPEN_SPECIAL_FLAGS
    for flags in flag_values:
        for scenario in ("fresh", "existing", "missing"):
            name = "open.flags.%#x.%s" % (flags, scenario)
            rows.append(row(name, flags, scenario, open_expect(flags, scenario)))
    return rows


def open_expect(flags, scenario):
    # Unknown high bits are ignored: the contract constrains only the four
    # documented flags (RDONLY/RDWR/CREATE/EXCL).
    rdonly = (flags & 0x0001) != 0
    rdwr = (flags & 0x0002) != 0
    create = (flags & 0x0004) != 0
    excl = (flags & 0x0008) != 0
    if rdonly == rdwr:
        return "EINVAL"
    if create and not rdwr:
        return "EINVAL"
    if excl and not create:
        return "EINVAL"
    if scenario == "fresh":
        if not create:
            return "ENOENT"
        return "OK"
    if scenario == "existing":
        if excl:
            return "EEXIST"
        return "OK"
    if not create:
        return "ENOENT"
    return "OK"


def append_rows():
    rows = []
    for size in PAYLOAD_SIZES:
        for count in (1, 2, 4, 8):
            name = "append.size.%d.count.%d" % (size, count)
            sizes = tuple([size] * count)
            expect = append_expect(sizes)
            rows.append(row(name, sizes, count, expect, None, None,
                            1 if expect == "OK" else None,
                            1 + count if expect == "OK" else None))
    specials = [
        ("append.zero_count", (1, 2), 0, "EINVAL"),
        ("append.null_array", (1, 2), 2, "EINVAL"),
        ("append.null_data_nonzero", (1, 2), 2, "EINVAL"),
        ("append.count_over_u32", (1,), UINT32_MAX + 1, "ERANGE"),
        ("append.huge_size_null", (0x7FFFFFFFFFFFFFFF,), 1, "ERANGE"),
        ("append.size_zero_null_ok", (0, 0), 2, "OK"),
        ("append.mixed_valid", (0, 1, 0, 7), 4, "OK"),
    ]
    for name, sizes, count, expect in specials:
        null_array = name == "append.null_array"
        null_data = 0 if name in ("append.null_data_nonzero",
                                  "append.huge_size_null") else None
        first = 1 if expect == "OK" else None
        end = 1 + count if expect == "OK" else None
        rows.append(row(name, tuple(sizes), count, expect, null_array,
                        null_data, first, end))
    return rows


def append_expect(sizes):
    if any(size > MAX_RECORD for size in sizes):
        return "ERANGE"
    return "OK"


FIXTURE_ABC = (b"", b"a", b"hello", b"0123456789")
FIXTURE_MIXED = (b"x", b"", b"yz", b"", b"tail")


def read_rows():
    rows = []
    fixture = FIXTURE_ABC
    indices = [0, 1, 2, 3, 4, 5, 6, 7, UINT64_MAX]
    capacities = list(range(0, 17)) + [31, 32, 63, 64, 65, 127, 128]
    for index in indices:
        for capacity in capacities:
            for null_buffer in (False, True):
                expect, size = read_expect(fixture, index, capacity, null_buffer)
                name = "read.idx.%d.cap.%d.null.%d" % (
                    index, capacity, int(null_buffer))
                rows.append(row(name, "abc", index, capacity, null_buffer,
                                expect, size))
    return rows


def read_expect(fixture, index, capacity, null_buffer):
    first = 1
    end = first + len(fixture)
    if index < first:
        return "EGONE", None
    if index >= end:
        return "ENOENT", None
    size = len(fixture[index - first])
    if null_buffer:
        return "OK", size
    if capacity < size:
        return "ETOOSMALL", size
    return "OK", size


def iter_rows():
    rows = []
    fixture = FIXTURE_MIXED
    starts = [0, 1, 2, 3, 4, 5, 6, 7, UINT64_MAX]
    capacities = list(range(0, 17)) + [31, 32, 63, 64]
    for start in starts:
        for capacity in capacities:
            for null_buffer in (False, True):
                expect = iter_expect(fixture, start)
                name = "iter.from.%d.cap.%d.null.%d" % (
                    start, capacity, int(null_buffer))
                rows.append(row(name, "mixed", start, capacity, null_buffer,
                                expect))
    return rows


def iter_expect(fixture, start):
    first = 1
    end = first + len(fixture)
    if start < first:
        return "EGONE"
    if start > end:
        return "ERANGE"
    return "OK"


def truncate_rows():
    rows = []
    setups = ("clean3", "clean1", "pruned")
    positions = list(range(0, 9)) + [0x100000000, UINT64_MAX]
    for setup in setups:
        for position in positions:
            name = "truncate.%s.from.%d" % (setup, position)
            rows.append(row(name, setup, position,
                            truncate_expect(setup, position)))
    return rows


def truncate_expect(setup, position):
    if setup == "clean3":
        first, end = 1, 4
    elif setup == "clean1":
        first, end = 1, 2
    else:
        first, end = 4, 5
    if position < first:
        return "EGONE"
    if position > end:
        return "ERANGE"
    return "OK"


def prune_rows():
    rows = []
    setups = ("rotated3", "dirty", "single")
    requests = list(range(0, 12)) + [0x100000000, UINT64_MAX]
    for setup in setups:
        for request in requests:
            name = "prune.%s.req.%d" % (setup, request)
            rows.append(row(name, setup, request, prune_expect(setup, request)))
    return rows


def prune_expect(setup, request):
    if setup == "rotated3":
        stable = 7
    elif setup == "dirty":
        stable = 4
    else:
        stable = 2
    if request > stable:
        return "EUNSTABLE"
    return "OK"


def strerror_rows():
    rows = []
    values = (list(range(-64, 33))
              + [1000, 0x7FFFFFFF, -0x80000000])
    for value in values:
        rows.append(row("strerror.%d" % value, value))
    return rows


def u64_rows():
    rows = []
    for a in BOUNDARY_VALUES:
        for b in BOUNDARY_VALUES:
            if a < b:
                sign = -1
            elif a > b:
                sign = 1
            else:
                sign = 0
            rows.append(row("u64.cmp.%d.%d" % (a, b), a, b, sign))
    return rows


# ---------------------------------------------------------------------------
# Format tables
# ---------------------------------------------------------------------------

VALUE_SPECS = [
    "set:00",
    "set:01",
    "set:02",
    "set:03",
    "set:7f",
    "set:80",
    "set:fe",
    "set:ff",
    "xor:01",
    "xor:02",
    "xor:04",
    "xor:08",
    "xor:10",
    "xor:20",
    "xor:40",
    "xor:80",
    "xor:ff",
    "add:01",
    "sub:01",
    "swap:00",
]


def part_header_regions(prefix):
    return [
        (prefix, "header.magic", 0, 8),
        (prefix, "header.uuid", 8, 16),
        (prefix, "header.file_id", 24, 8),
        (prefix, "header.revision", 32, 8),
        (prefix, "header.first", 40, 8),
        (prefix, "header.version", 48, 4),
        (prefix, "header.reserved", 52, 4),
        (prefix, "header.crc", 56, 4),
        (prefix, "header.reserved2", 60, 4),
    ]


def marker_regions(prefix, index, offset):
    return [
        (prefix, "marker[%d].magic" % index, offset, 8),
        (prefix, "marker[%d].uuid" % index, offset + 8, 16),
        (prefix, "marker[%d].file_id" % index, offset + 24, 8),
        (prefix, "marker[%d].revision" % index, offset + 32, 8),
        (prefix, "marker[%d].end" % index, offset + 40, 8),
        (prefix, "marker[%d].version" % index, offset + 48, 4),
        (prefix, "marker[%d].crc" % index, offset + 52, 4),
        (prefix, "marker[%d].trailer" % index, offset + 56, 8),
    ]


def batch_size(sizes):
    return 32 + sum(4 + size + 4 for size in sizes) + 24


def batch_regions(prefix, index, offset, first, sizes):
    regions = [
        (prefix, "batch[%d].magic" % index, offset, 4),
        (prefix, "batch[%d].count" % index, offset + 4, 4),
        (prefix, "batch[%d].first" % index, offset + 8, 8),
        (prefix, "batch[%d].bytes" % index, offset + 16, 8),
        (prefix, "batch[%d].header_crc" % index, offset + 24, 4),
        (prefix, "batch[%d].reserved" % index, offset + 28, 4),
    ]
    position = offset + 32
    for record, size in enumerate(sizes):
        regions.append((prefix, "batch[%d].record[%d].length" % (index, record),
                        position, 4))
        regions.append((prefix, "batch[%d].record[%d].payload" % (index, record),
                        position + 4, size))
        regions.append((prefix, "batch[%d].record[%d].crc" % (index, record),
                        position + 4 + size, 4))
        position += 4 + size + 4
    footer = offset + batch_size(sizes) - 24
    regions += [
        (prefix, "batch[%d].footer_magic" % index, footer, 4),
        (prefix, "batch[%d].footer_count" % index, footer + 4, 4),
        (prefix, "batch[%d].footer_last" % index, footer + 8, 8),
        (prefix, "batch[%d].footer_crc" % index, footer + 16, 4),
        (prefix, "batch[%d].footer_reserved" % index, footer + 20, 4),
    ]
    return regions, footer + 24


def part_regions(prefix, markers, batches, sealed):
    """markers: list of marker end values; batches: list of (first, sizes)."""
    regions = part_header_regions(prefix)
    offset = 64
    for index, end in enumerate(markers):
        regions += marker_regions(prefix, index, offset)
        offset += 64
        if index < len(batches):
            first, sizes = batches[index]
            batch, offset = batch_regions(prefix, index, offset, first, sizes)
            regions += batch
    if sealed:
        regions += [
            (prefix, "sealed.magic", offset, 8),
            (prefix, "sealed.uuid", offset + 8, 16),
            (prefix, "sealed.file_id", offset + 24, 8),
            (prefix, "sealed.first", offset + 32, 8),
            (prefix, "sealed.end", offset + 40, 8),
            (prefix, "sealed.records", offset + 48, 8),
            (prefix, "sealed.digest", offset + 56, 4),
            (prefix, "sealed.crc", offset + 60, 4),
        ]
    return regions


def manifest_regions(sealed_count):
    regions = [
        ("MANIFEST", "magic", 0, 8),
        ("MANIFEST", "generation", 8, 8),
        ("MANIFEST", "uuid", 16, 16),
        ("MANIFEST", "revision", 32, 8),
        ("MANIFEST", "first", 40, 8),
        ("MANIFEST", "sealed_count", 48, 4),
        ("MANIFEST", "version", 52, 4),
        ("MANIFEST", "header_crc", 56, 4),
        ("MANIFEST", "reserved", 60, 4),
    ]
    offset = 64
    for index in range(sealed_count):
        regions.append(("MANIFEST", "sealed[%d]" % index, offset, 24))
        offset += 24
    regions.append(("MANIFEST", "active", offset, 16))
    offset += 16
    regions.append(("MANIFEST", "crc", offset, 4))
    return regions


FIXTURES = {
    "two_parts": {
        "current_generation": 2,
        "manifest_sealed": 1,
        "manifest_size": 108,
        "parts": [
            ("part.0000000000000001", "part.sealed", [1, 4],
             [(1, [1, 1, 1])], True, 339),
            ("part.0000000000000002", "part.active", [4, 7],
             [(4, [1, 1, 1])], False, 275),
        ],
    },
    "three_parts": {
        "current_generation": 3,
        "manifest_sealed": 2,
        "manifest_size": 132,
        "parts": [
            ("part.0000000000000001", "part.sealed", [1, 4],
             [(1, [1, 1, 1])], True, 339),
            ("part.0000000000000002", "part.sealed", [4, 7],
             [(4, [1, 1, 1])], True, 339),
            ("part.0000000000000003", "part.active", [7, 8],
             [(7, [1])], False, 257),
        ],
    },
}


def fixture_regions(fixture):
    spec = FIXTURES[fixture]
    regions = [
        ("CURRENT", "CURRENT", "magic", 0, 8),
        ("CURRENT", "CURRENT", "generation", 8, 8),
        ("CURRENT", "CURRENT", "version", 16, 4),
        ("CURRENT", "CURRENT", "crc", 20, 4),
        ("CURRENT", "CURRENT", "reserved", 24, 8),
    ]
    for kind, region, offset, size in manifest_regions(spec["manifest_sealed"]):
        regions.append((kind, None, region, offset, size))
    for name, kind, markers, batches, sealed, _size in spec["parts"]:
        for _kind, region, offset, size in part_regions(name, markers, batches,
                                                        sealed):
            regions.append((kind, name, region, offset, size))
    return regions


def classify(file_kind, region):
    if region == "header.reserved":
        return ("open", ("ECORRUPT",))
    if file_kind == "MANIFEST" and region == "reserved":
        return ("open", ("ECORRUPT",))
    if region.endswith("reserved") or region.endswith("reserved2"):
        return ("open", ("OK",))
    if file_kind in ("CURRENT", "MANIFEST"):
        if region == "version":
            return ("open", ("EFORMAT",))
        return ("open", ("ECORRUPT",))
    if region == "header.version":
        return ("open", ("ECORRUPT",))
    if region.startswith("marker["):
        if region.endswith(".trailer"):
            return ("open", ("OK", "ECORRUPT"))
        if file_kind == "part.sealed":
            return ("open", ("ECORRUPT",))
        return ("open", ("OK", "ECORRUPT"))
    if region.startswith("batch[") and ".record[" in region:
        if (region.endswith(".payload") or region.endswith(".crc")
                or region.endswith(".length")):
            return ("read", ("ECORRUPT",))
    if ".footer_crc" in region:
        return ("verify", ("ECORRUPT",))
    if region.startswith("sealed."):
        return ("open", ("ECORRUPT",))
    return ("open", ("ECORRUPT",))


def corrupt_rows():
    rows = []
    for fixture in FIXTURES:
        for file_kind, file_name, region, offset, size in fixture_regions(fixture):
            check, allowed = classify(file_kind, region)
            for relative in range(size):
                for spec_value in VALUE_SPECS:
                    name = "corrupt.%s.%s.%s.%d.%s" % (
                        fixture,
                        file_kind.replace(".", "_"),
                        region.replace("[", "_").replace("]", "").replace(".", "_"),
                        relative,
                        spec_value.replace(":", "_"),
                    )
                    rows.append(row(name, fixture, file_kind, file_name, region,
                                    offset + relative, spec_value, check,
                                    allowed))
    return rows


def truncate_file_rows():
    rows = []
    for fixture, spec in FIXTURES.items():
        for length in range(0, 32):
            rows.append(row("trunc.%s.CURRENT.%d" % (fixture, length), fixture,
                            "CURRENT", "CURRENT", length,
                            ("ECORRUPT", "EFORMAT", "ENOENT")))
        for length in range(0, spec["manifest_size"]):
            rows.append(row("trunc.%s.MANIFEST.%d" % (fixture, length),
                            fixture, "MANIFEST", None, length,
                            ("ECORRUPT", "EFORMAT", "ENOENT")))
        for name, kind, _markers, _batches, sealed, size in spec["parts"]:
            allowed = (("ECORRUPT", "EFORMAT") if sealed
                       else ("OK", "ECORRUPT", "EFORMAT"))
            for length in range(0, size):
                rows.append(row("trunc.%s.%s.%s.%d" % (fixture, kind, name,
                                                       length),
                                fixture, kind, name, length, allowed))
    return rows


def format_field_rows():
    """Concrete expected fields for the two-parts fixture."""
    rows = []
    rows.append(row("field.CURRENT.magic", "CURRENT", "magic", "LD89CUR2"))
    rows.append(row("field.CURRENT.generation", "CURRENT", "generation", 2))
    rows.append(row("field.CURRENT.version", "CURRENT", "version", 2))
    rows.append(row("field.CURRENT.reserved", "CURRENT", "reserved", 0))
    rows.append(row("field.MANIFEST.magic", "MANIFEST", "magic", "LD89MAN2"))
    rows.append(row("field.MANIFEST.generation", "MANIFEST", "generation", 2))
    rows.append(row("field.MANIFEST.revision", "MANIFEST", "revision", 0))
    rows.append(row("field.MANIFEST.first", "MANIFEST", "first", 1))
    rows.append(row("field.MANIFEST.sealed_count", "MANIFEST", "sealed_count", 1))
    rows.append(row("field.MANIFEST.version", "MANIFEST", "version", 2))
    rows.append(row("field.MANIFEST.sealed[0].file_id", "MANIFEST",
                    "sealed[0].file_id", 1))
    rows.append(row("field.MANIFEST.sealed[0].first", "MANIFEST",
                    "sealed[0].first", 1))
    rows.append(row("field.MANIFEST.sealed[0].end", "MANIFEST",
                    "sealed[0].end", 4))
    rows.append(row("field.MANIFEST.active.file_id", "MANIFEST",
                    "active.file_id", 2))
    rows.append(row("field.MANIFEST.active.first", "MANIFEST",
                    "active.first", 4))
    rows.append(row("field.part1.header.magic", "part.0000000000000001",
                    "header.magic", "LD89PRT2"))
    rows.append(row("field.part1.header.file_id", "part.0000000000000001",
                    "header.file_id", 1))
    rows.append(row("field.part1.header.revision", "part.0000000000000001",
                    "header.revision", 0))
    rows.append(row("field.part1.header.first", "part.0000000000000001",
                    "header.first", 1))
    rows.append(row("field.part1.header.version", "part.0000000000000001",
                    "header.version", 2))
    rows.append(row("field.part1.marker0.end", "part.0000000000000001",
                    "marker[0].end", 1))
    rows.append(row("field.part1.marker1.end", "part.0000000000000001",
                    "marker[1].end", 4))
    rows.append(row("field.part1.marker1.trailer", "part.0000000000000001",
                    "marker[1].trailer", "89STABLE"))
    rows.append(row("field.part1.batch0.first", "part.0000000000000001",
                    "batch[0].first", 1))
    rows.append(row("field.part1.batch0.count", "part.0000000000000001",
                    "batch[0].count", 3))
    rows.append(row("field.part1.batch0.bytes", "part.0000000000000001",
                    "batch[0].bytes", 83))
    rows.append(row("field.part1.batch0.record0.length",
                    "part.0000000000000001", "batch[0].record[0].length", 1))
    rows.append(row("field.part1.batch0.record2.length",
                    "part.0000000000000001", "batch[0].record[2].length", 1))
    rows.append(row("field.part1.footer.magic", "part.0000000000000001",
                    "batch[0].footer_magic", "b89\x02"))
    rows.append(row("field.part1.footer.count", "part.0000000000000001",
                    "batch[0].footer_count", 3))
    rows.append(row("field.part1.footer.last", "part.0000000000000001",
                    "batch[0].footer_last", 3))
    rows.append(row("field.part1.sealed.magic", "part.0000000000000001",
                    "sealed.magic", "LD89SGF2"))
    rows.append(row("field.part1.sealed.file_id", "part.0000000000000001",
                    "sealed.file_id", 1))
    rows.append(row("field.part1.sealed.first", "part.0000000000000001",
                    "sealed.first", 1))
    rows.append(row("field.part1.sealed.end", "part.0000000000000001",
                    "sealed.end", 4))
    rows.append(row("field.part1.sealed.records", "part.0000000000000001",
                    "sealed.records", 3))
    rows.append(row("field.part2.header.file_id", "part.0000000000000002",
                    "header.file_id", 2))
    rows.append(row("field.part2.header.first", "part.0000000000000002",
                    "header.first", 4))
    rows.append(row("field.part2.marker0.end", "part.0000000000000002",
                    "marker[0].end", 4))
    rows.append(row("field.part2.marker1.end", "part.0000000000000002",
                    "marker[1].end", 7))
    rows.append(row("field.part2.batch0.first", "part.0000000000000002",
                    "batch[0].first", 4))
    rows.append(row("field.part2.batch0.count", "part.0000000000000002",
                    "batch[0].count", 3))
    return rows


# ---------------------------------------------------------------------------
# Fault, crash, adversarial, latency tables
# ---------------------------------------------------------------------------

FAULT_SCENARIOS = [
    "append",
    "appendv",
    "appendv_at",
    "sync",
    "truncate",
    "truncate_mid",
    "prune",
    "rotate",
    "rotate_empty",
    "recover",
    "read",
    "verify",
]

FAULT_OPS = [
    "open",
    "close",
    "pread",
    "pwrite",
    "fstat",
    "ftruncate",
    "fsync",
    "fdatasync",
    "rename",
    "unlink",
    "mkdir",
    "flock",
    "opendir",
    "readdir",
    "closedir",
]


def fault_rows():
    rows = []
    for scenario in FAULT_SCENARIOS:
        for op in FAULT_OPS:
            for nth in range(1, 13):
                for mode, err in (("fail", "EIO"), ("eintr", "EINTR"),
                                  ("short", "EIO")):
                    name = "fault.%s.%s.%d.%s" % (scenario, op, nth, mode)
                    expect = "ok" if mode == "eintr" else "error"
                    if scenario in ("read", "verify"):
                        expect = "any"
                    rows.append(row(name, scenario, op, nth, mode, err, expect))
    return rows


CRASH_OPS = ["pwrite", "fsync", "fdatasync", "ftruncate", "rename", "unlink",
             "mkdir", "open"]


def crash_rows():
    rows = []
    for scenario in FAULT_SCENARIOS:
        for op in CRASH_OPS:
            for nth in range(1, 11):
                name = "crash.%s.%s.%d" % (scenario, op, nth)
                rows.append(row(name, scenario, op, nth))
    return rows


PATH_KINDS = [
    ("empty", "EINVAL"),
    ("dot", "ENOENT"),
    ("dotdot", "ENOENT"),
    ("missing", "ENOENT"),
    ("nested_missing", "ENOENT"),
    ("file_as_dir", "ENOENT"),
    ("trailing_slash", "ENOENT"),
    ("long_255", "ENOENT"),
    ("long_4095", "ENOENT"),
    ("long_4096", "ENOENT"),
    ("long_8192", "EINVAL"),
    ("symlink_dir", "OK"),
    ("symlink_loop", "ENOENT"),
    ("symlink_file", "ENOENT"),
    ("fifo", "ENOENT"),
    ("empty_component", "ENOENT"),
    ("dot_component", "ENOENT"),
    ("absolute_missing", "ENOENT"),
    ("space_name", "ENOENT"),
    ("newline_name", "ENOENT"),
    ("tab_name", "ENOENT"),
    ("dash_name", "ENOENT"),
    ("unicode_name", "ENOENT"),
    ("dotfile_name", "ENOENT"),
    ("deep_nested", "ENOENT"),
    ("double_slash", "ENOENT"),
    ("backslash_name", "ENOENT"),
    ("percent_name", "ENOENT"),
    ("colon_name", "ENOENT"),
    ("quote_name", "ENOENT"),
]


def path_rows():
    rows = []
    for kind, expect in PATH_KINDS:
        rows.append(row("path.%s" % kind, kind, expect))
    for length in range(1, 33):
        rows.append(row("path.name_len.%d" % length, "name_len:%d" % length,
                        "ENOENT"))
    return rows


LIMIT_CONFIGS = [
    ("as_16m", 16 * 1024 * 1024, None, None, "create", "error"),
    ("as_32m", 32 * 1024 * 1024, None, None, "create", "error"),
    ("as_48m", 48 * 1024 * 1024, None, None, "create", "any"),
    ("as_64m", 64 * 1024 * 1024, None, None, "create", "any"),
    ("as_96m", 96 * 1024 * 1024, None, None, "append", "any"),
    ("as_128m", 128 * 1024 * 1024, None, None, "append_huge", "error"),
    ("as_256m", 256 * 1024 * 1024, None, None, "append_huge", "any"),
    ("fsize_1k", None, 1024, None, "append", "error"),
    ("fsize_4k", None, 4096, None, "append", "error"),
    ("fsize_16k", None, 16384, None, "append", "error"),
    ("fsize_64k", None, 65536, None, "append", "error"),
    ("fsize_256k", None, 262144, None, "append", "any"),
    ("fsize_1m", None, 1024 * 1024, None, "append", "error"),
    ("nofile_8", None, None, 8, "open", "error"),
    ("nofile_12", None, None, 12, "open", "any"),
    ("nofile_16", None, None, 16, "open", "any"),
    ("nofile_24", None, None, 24, "open", "any"),
    ("nofile_32", None, None, 32, "open", "any"),
    ("nofile_48", None, None, 48, "many_parts", "any"),
    ("nofile_64", None, None, 64, "many_parts", "any"),
]


def limit_rows():
    rows = []
    for name, as_bytes, fsize, nofile, scenario, expect in LIMIT_CONFIGS:
        rows.append(row("limit.%s" % name, as_bytes, fsize, nofile, scenario,
                        expect))
    return rows


LATENCY_ROWS = [
    ("latency.append.1.64", "append", 64, 1, 50.0),
    ("latency.append.32.64", "appendv", 64, 32, 100.0),
    ("latency.append.256.64", "appendv", 64, 256, 200.0),
    ("latency.append.1.4096", "append", 4096, 1, 50.0),
    ("latency.append.1.1048576", "append", 1048576, 1, 500.0),
    ("latency.append.16.65536", "appendv", 65536, 16, 500.0),
    ("latency.sync.clean", "sync", 0, 1, 100.0),
    ("latency.sync.dirty", "sync_dirty", 64, 32, 200.0),
    ("latency.read.64", "read", 64, 1, 50.0),
    ("latency.read.4096", "read", 4096, 1, 50.0),
    ("latency.read.1048576", "read", 1048576, 1, 200.0),
    ("latency.read.size_only", "read_meta", 64, 1, 50.0),
    ("latency.iter.1000", "iterate", 64, 1000, 500.0),
    ("latency.rotate", "rotate", 64, 32, 200.0),
    ("latency.prune", "prune", 64, 32, 300.0),
    ("latency.verify.1000", "verify", 64, 1000, 2000.0),
    ("latency.open.1000", "open", 64, 1000, 2000.0),
]

SCALING_ROWS = [
    ("scaling.append", "append", 1000, 2000, 6.0),
    ("scaling.read", "read", 1000, 2000, 6.0),
    ("scaling.open", "open", 1000, 2000, 6.0),
    ("scaling.iterate", "iterate", 1000, 2000, 6.0),
    ("scaling.sync", "sync_many", 100, 200, 6.0),
]


def main():
    emit(
        "tables_api.py",
        '"""Generated API case tables. Rows are executed by cases_api.py."""\n',
        [
            ("OPEN_ROWS", open_rows()),
            ("APPEND_ROWS", append_rows()),
            ("READ_ROWS", read_rows()),
            ("ITER_ROWS", iter_rows()),
            ("TRUNCATE_ROWS", truncate_rows()),
            ("PRUNE_ROWS", prune_rows()),
            ("STRERROR_ROWS", strerror_rows()),
            ("U64_ROWS", u64_rows()),
        ],
    )
    emit(
        "tables_format.py",
        '"""Generated format and corruption tables. Executed by cases_format.py\nand cases_corrupt.py."""\n',
        [
            ("FIELD_ROWS", format_field_rows()),
            ("CORRUPT_ROWS", corrupt_rows()),
            ("TRUNCATE_FILE_ROWS", truncate_file_rows()),
        ],
    )
    emit(
        "tables_fault.py",
        '"""Generated fault and crash tables. Executed by cases_fault.py and\ncases_crash.py."""\n',
        [
            ("FAULT_ROWS", fault_rows()),
            ("CRASH_ROWS", crash_rows()),
        ],
    )
    emit(
        "tables_adversarial.py",
        '"""Generated adversarial tables. Executed by cases_adversarial.py."""\n',
        [
            ("PATH_ROWS", path_rows()),
            ("LIMIT_ROWS", limit_rows()),
        ],
    )
    emit(
        "tables_latency.py",
        '"""Generated latency tables. Executed by cases_latency.py."""\n',
        [
            ("LATENCY_ROWS", [row(*fields) for fields in LATENCY_ROWS]),
            ("SCALING_ROWS", [row(*fields) for fields in SCALING_ROWS]),
        ],
    )
    for name in (
        "tables_api.py",
        "tables_format.py",
        "tables_fault.py",
        "tables_adversarial.py",
        "tables_latency.py",
    ):
        path = os.path.join(HERE, name)
        with open(path) as handle:
            lines = handle.readlines()
        print("%-24s %6d lines" % (name, len(lines)))


if __name__ == "__main__":
    main()
