# Generated by gen_tables.py; do not edit by hand.
"""Generated latency tables. Executed by cases_latency.py."""

LATENCY_ROWS = [
    ('latency.append.1.64', 'append', 64, 1, 50.0),
    ('latency.append.32.64', 'appendv', 64, 32, 100.0),
    ('latency.append.256.64', 'appendv', 64, 256, 200.0),
    ('latency.append.1.4096', 'append', 4096, 1, 50.0),
    ('latency.append.1.1048576', 'append', 1048576, 1, 500.0),
    ('latency.append.16.65536', 'appendv', 65536, 16, 500.0),
    ('latency.sync.clean', 'sync', 0, 1, 100.0),
    ('latency.sync.dirty', 'sync_dirty', 64, 32, 200.0),
    ('latency.read.64', 'read', 64, 1, 50.0),
    ('latency.read.4096', 'read', 4096, 1, 50.0),
    ('latency.read.1048576', 'read', 1048576, 1, 200.0),
    ('latency.read.size_only', 'read_meta', 64, 1, 50.0),
    ('latency.iter.1000', 'iterate', 64, 1000, 500.0),
    ('latency.rotate', 'rotate', 64, 32, 200.0),
    ('latency.prune', 'prune', 64, 32, 300.0),
    ('latency.verify.1000', 'verify', 64, 1000, 2000.0),
    ('latency.open.1000', 'open', 64, 1000, 2000.0),
]

SCALING_ROWS = [
    ('scaling.append', 'append', 1000, 2000, 6.0),
    ('scaling.read', 'read', 1000, 2000, 6.0),
    ('scaling.open', 'open', 1000, 2000, 6.0),
    ('scaling.iterate', 'iterate', 1000, 2000, 6.0),
    ('scaling.sync', 'sync_many', 100, 200, 6.0),
]
