#ifndef CAT89_FREE_H
#define CAT89_FREE_H

#include <cat89/alloc.h>
#include <cat89/core.h>

/* cat89_free.h - free category generated by a directed graph.
 *
 * Objects are (interned) vertex handles; morphisms are finite directed paths
 * (edge sequences) under concatenation, the empty path being the identity.
 * Distinct paths remain distinct even when they share endpoints. The graph
 * provider (not libcat89) supplies edge endpoints and vertex identity. */

typedef struct cat89_free_graph_ops
{
    int (*vertex_same)(void *ctx, const void *a, const void *b);

    const void *(*edge_source)(void *ctx, const void *edge);

    const void *(*edge_target)(void *ctx, const void *edge);
} cat89_free_graph_ops;

/* Build the free category over the provider graph. vertex_same, edge_source
 * and edge_target are required. */
cat89_status cat89_free_category_new(const cat89_free_graph_ops *ops,
                                     void *graph_ctx,
                                     const cat89_allocator *allocator,
                                     cat89_category **out_category);

/* Borrowed object handle (interned) for a graph vertex. */
cat89_status cat89_free_obj(cat89_category *category, const void *vertex,
                            const cat89_obj **out_obj);

/* One owned length-1 path morphism along `edge`. */
cat89_status cat89_free_edge(cat89_category *category, const void *edge,
                             cat89_mor **out_mor);

#endif
