#!/usr/bin/env python3
"""Generate src/cksum89_tables.c from the frozen reflected polynomials.

The checked-in tables are verified entry-by-entry against independent
Rocksoft remainders by the test suite, so this generator is a development
convenience, not the authority. Regenerate with `just tables`.
"""

import sys

ALGORITHMS = {
    "crc32_iso_hdlc": 0x04C11DB7,
    "crc32c": 0x1EDC6F41,
    "crc64_nvme": 0xAD93D23594C93659,
}

HEADER = """/*
 * cksum89_tables.c - checked-in reflected lookup tables.
 *
 * Generated by tools/gen_tables.py; the test suite verifies every entry
 * against an independent Rocksoft remainder, so this file is not
 * authoritative. Regenerate with `just tables`.
 */

#include "cksum89_internal.h"
"""


def reflect(value, width):
    result = 0
    for _ in range(width):
        result = (result << 1) | (value & 1)
        value >>= 1
    return result


def entry(poly, width, index):
    reflected = reflect(poly, width)
    crc = index
    for _ in range(8):
        if crc & 1:
            crc = (crc >> 1) ^ reflected
        else:
            crc >>= 1
    return crc & ((1 << width) - 1)


def emit_u32(name, poly):
    lines = ["", "const cksum89_u32 %s[256] = {" % name]
    for base in range(0, 256, 4):
        row = ["0x%08xUL" % entry(poly, 32, base + i) for i in range(4)]
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    return lines


def emit_u64(name, poly):
    lines = ["", "const cksum89_u64 %s[256] = {" % name]
    for base in range(0, 256, 2):
        row = []
        for i in range(2):
            value = entry(poly, 64, base + i)
            row.append("{0x%08xUL, 0x%08xUL}" % (value >> 32, value & 0xFFFFFFFF))
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    return lines


def main(argv):
    selected = argv[1:] if len(argv) > 1 else list(ALGORITHMS)
    unknown = [name for name in selected if name not in ALGORITHMS]
    if unknown:
        sys.stderr.write("unknown table: %s\n" % ", ".join(unknown))
        return 2
    lines = [HEADER.rstrip("\n")]
    for name in selected:
        poly = ALGORITHMS[name]
        if name == "crc64_nvme":
            lines.extend(emit_u64("cksum89_%s_table" % name, poly))
        else:
            lines.extend(emit_u32("cksum89_%s_table" % name, poly))
    sys.stdout.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
